### ISSUE TITLE
Getting this to compile using cmake

### ISSUE THREAD

**Issue by AntonioCS** [TLeonardUK/ZombieGrinder#1]
Hey,

I've forked the project and I'm trying to move everything over to cmake.
With the help of @melak47 (and some others from #cmake and #build-systems channels) I got it compiling.
I'm now trying to see how to resolve some steam issues (as I don't have a steam account) as I'm getting this error:
```
[00:00:00:219, 0, 0.0mb] D:\Projects\Personal\cpp\Games\ZombieGrinder\Source\Engine\Engine\GameEngine.cpp:217
[00:00:00:219, 0, 0.0mb] m_online_platform->Init_Client()
[00:00:00:219, 0, 0.0mb] Message: Failed to initialize and connect to steam, are you sure it's running?
```

Just wanted to let someone know because I'm just happy I'm getting somewhere with this.
Thanks for making this public.

If you want, you can take a look at it here: https://github.com/AntonioCS/ZombieGrinder/tree/feature/exploration

**Comment by TLeonardUK** [comment]
Very cool! Surprised anyone is looking at this ancient codebase lol.

The error you are getting is because you don't have steam running. The game uses steam for a lot of different services - mod distribution, network communication, etc. There isn't a straightforward way to remove it, unless you fancy rewriting all the services it relies on steam for.

If you really don't want to use steam you can probably use a steam emulator to get it running.

**Comment by AntonioCS** [comment]
I've never used steam for anything, but I'll see what I can do. If it's just creating an account somewhere I'll do it.
I was hoping there would be a way to just bypass this but guess not :)

It might be old and boring to you but for a noob like me it's quite interesting. 
I find the whole process interesting. Seems you did everything yourself. 
You created your own cmake like thing that automated a lot of stuff, which looks really cool. 
You have your own custom engine.
There are all sorts of things I really don't understand (I have a reasonable understanding of basic C++).

If I can figure out some of this, I'll be happy.

Thanks again!
